name: Playstore deployment
on:
  push:
    branches:
      - hf-change-workflow
jobs:
  #CI
  build_android:
    name: Building Android 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.13.9
      - name: Install Flutter dependencies
        run: flutter pub get
        
      # Step to create the utils directory and configs.dart file
      - name: Create Configs File
        run: |
          mkdir -p lib/utils
          touch lib/utils/configs.dart
          echo "const String apiKey = '${{ secrets.API_KEY }}';" > lib/utils/configs.dart

      - name : Run tests
        run: flutter test --coverage
      - run: flutter build apk --no-tree-shake-icons
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.apk